### PR TITLE
Embed an actual font into the pdf. Fixes #191

### LINKED ISSUE #191: F in PDF scrambles could be mistaken for F'
The font used in the PDF files has a little serif hanging off of the upper-right of the F which could be mistaken for an apostrophe. I think it might be better to use a non-serif monospace font to avoid the similarity so that scramblers do not get confused.

### PR DESCRIPTION
**Pull request by gyroninja**
Currently embeds Liberation Mono into the pdf.

This currently adds the font into the jar file (while still supporting running tnoodle through ./tmt run) in a hacky way. There really isn't anything in place that would be suitable at the moment.

### CODE REVIEW

**Comment by jfly** [comment]
This looks like it's working for me! I see a slight file size increase in our PDFs (6499 bytes)

```
~/tmp/tnoodling @kaladin> pdffonts not-embedded-tnoodle-0.11.1.pdf 
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
Helvetica                            Type 1            WinAnsi          no  no  no      11  0
Courier                              Type 1            WinAnsi          no  no  no      12  0
~/tmp/tnoodling @kaladin> pdffonts embedded-tnoodle-post-0.11.1.pdf 
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
Helvetica                            Type 1            WinAnsi          no  no  no      11  0
ZSERAZ+LiberationMono                TrueType          WinAnsi          yes yes no      12  0
~/tmp/tnoodling @kaladin> ls -al
total 48
drwxr-sr-x  2 jeremy jeremy  4096 Aug 31 09:28 .
drwxrwsr-x 55 jeremy jeremy 12288 Aug 31 09:27 ..
-rw-r--r--  1 jeremy jeremy 18572 Aug 31 09:26 embedded-tnoodle-post-0.11.1.pdf
-rw-r--r--  1 jeremy jeremy 12073 Aug 31 09:27 not-embedded-tnoodle-0.11.1.pdf
```

I've posted these two files here [embedded-tnoodle-post-0.11.1.pdf](https://dl.dropboxusercontent.com/u/1463845/temp/embedded-tnoodle-post-0.11.1.pdf) and [not-embedded-tnoodle-0.11.1.pdf](https://dl.dropboxusercontent.com/u/1463845/temp/not-embedded-tnoodle-0.11.1.pdf), and am going to ask our delegates to post screenshots from both of them.

For example, on my computer:

# not-embedded-tnoodle-0.11.1.pdf
image

# embedded-tnoodle-post-0.11.1.pdf
image

**Comment by jfly** [comment]
From @jonatanklosko:

# Not embedded:

image
​
# Embedded:

image

**Comment by StachuDotNet** [comment]
http://imgur.com/a/zHNSO

**Comment by lgarron** [comment]
Looks pretty good to me!

The apostrophe is a tiny bit farther from the letter than I would like, but I would rather use the existing font than weak it.

**Comment by jfly** [comment]
That makes sense, @lgarron. I would guess that kerning doesn't apply to monospaced fonts, though?

**Comment by lgarron** [comment]
> I would guess that kerning doesn't apply to monospaced fonts, though?

It could. You could shift each letter within the fixed width based on adjacent letters.
I don't know of any monospace font that actually does this, though.

**Comment by jfly** [comment]
We got some good feedback from the board and other WCA committees/teams about this change, so I'm going to merge it up.

**Pull request merged**
