### PR TITLE
Update MegaminxPuzzle.java

### PR DESCRIPTION
**Pull request by Mollerz**
Change megaminx colour scheme from outdated mefferts scheme to mf8/Dayan/Shengshou/YuHu colour scheme.

### CODE REVIEW

**Comment by jfly** [comment]
2016-01-20_1783x794_kaladin

**Comment by jfly** [comment]
I haven't tried looking at hex colors, but did you darken our second darkest blue?

**Comment by Mollerz** [comment]
Yes, I took the darkblue from 0000ff to 0000b3. I asked some people on their thoughts on the colour changes and they all said the original blue was a bit too bright.

**Comment by jfly** [comment]
And purple stayed the same?

Can you provide some screenshots justifying the change? To my eyes, our dark blue and our purple are much harder to distinguish than they were previously.

**Comment by Mollerz** [comment]
The purple was also made darker. Both the purple and the blue are quite dark on the scheme, the picture attached is in bright lighting. On the screenshot they do look quite similar, however I can personally quite easily distinguish between the colours with f.lux activated right now. I think we could easily make the purple slightly lighter.

img_20160120_214602

**Comment by jfly** [comment]
I believe we should optimize for highest contrast, rather than real life accuracy.

**Comment by Mollerz** [comment]
I increased the lightness of the purple by 30%, try that.

**Comment by jfly** [comment]
That looks *much* better:

2016-01-20_1766x766_kaladin

**Comment by Mollerz** [comment]
Agreed!

**Comment by jfly** [comment]
Looks like the test passed. I'm happy with this. @lgarron, what do you think?

**Comment by lgarron** [comment]
> @lgarron, what do you think?

Looks nice to me!

**Comment by jfly** [comment]
Ok, merged!

**Pull request merged**
